In [5]:
import numpy as np
a=np.array(([1,2,3,4]))
print(a)

[1 2 3 4]


In [4]:
import time
a=np.random.rand(1000000)
b=np.random.rand(1000000)
tic=time.time()
c=np.dot(a,b)
toc=time.time()
print('Vectorized version:',str(toc-tic),'ms')
c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()
print('for loop:',str(toc-tic),'ms')
#结论：用向量化代替显示for循环

Vectorized version: 0.001951456069946289 ms
for loop: 0.48470449447631836 ms


In [6]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [7]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [8]:
np.abs(a)

array([1, 2, 3, 4])

In [9]:
np.maximum(a,a)

array([1, 2, 3, 4])

In [10]:
a.reshape(1,4)

array([[1, 2, 3, 4]])

In [12]:
b=np.array([[1,2,3,4]])
assert(a.shape==(1,4))

AssertionError: 